name: infra
description: "A Porter bundle to install my testing infra on k8s"
version: 0.1.0
tag: vdice.azurecr.io/infra

mixins:
  - exec

credentials:
  - name: kubeconfig
    path: /root/.kube/config

dependencies:
  # Auxiliary
  - name: cert-manager
    tag: ghcr.io/vdice/cert-manager:v0.1.0
      
  - name: nginx-ingress
    tag: ghcr.io/vdice/nginx-ingress:v0.1.0

  - name: nfs
    tag: ghcr.io/vdice/nfs:v0.1.0

  # Brigade server and GH gateway
  - name: brigade
    tag: ghcr.io/vdice/brigade:v0.1.0

  - name: brigade-github-app
    tag: ghcr.io/vdice/brigade-github-app:v0.1.0

  # Brigade projects
  # Uses same bundle but with different values
  - name: github-vdice-brigade
    tag: ghcr.io/vdice/brigade-project:v0.1.0

  - name: github-vdice-cnab-spec
    tag: ghcr.io/vdice/brigade-project:v0.1.0

# TODO: it would be nice to support a "no-mixin"/no-op step, to reduce YAML
install:
  - exec:
      description: "Install testing infra"
      command: sh

status:
  - exec:
      description: "Check testing infra"
      command: sh

upgrade:
  - exec:
      description: "Upgrade testing infra"
      command: sh

uninstall:
  - exec:
      description: "Uninstall testing infra"
      command: sh