version: "3.6"
services:
  hello:
    image: busybox
    command: ["echo", "${hello_text}", ">", "/root/echo.txt"]
    ports:
      - ${hello_port}:5678
    volumes:
      - myvol:/root
volumes:
  myvol:
    external: true