FROM debian:stretch

ARG BUNDLE_DIR

RUN apt-get update && apt-get install -y ca-certificates git

RUN git clone git://github.com/technosophos/gh-build-badge.git $BUNDLE_DIR/gh-build-badge

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR