name: ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Bundles
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Porter
        uses: getporter/gh-action@v0.1.1
      - name: Bootstrap
        run: make bootstrap
      - name: Build
        run: make build-bundle
      - name: Validate
        run: make validate-bundle
  publish-ghcr:
    needs: build
    name: Publish Bundles to the ghcr.io Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Porter
        uses: getporter/gh-action@v0.1.1
      - name: Login to the ghcr.io Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Publish
        run: REGISTRY=ghcr.io/vdice make publish-bundle 
  publish-docker:
    needs: build
    name: Publish Bundles to the docker.io Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Porter
        uses: getporter/gh-action@v0.1.1
      - name: Login to the docker.io Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish
        run: REGISTRY=vdice make publish-bundle