name: ci

on:
  push:
    branches: [ master ]

jobs:
  publish-ghcr:
    name: Publish Bundles to the ghcr.io Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Porter
        uses: getporter/gh-action@v0.1.3
      - name: Get Mixins
        run: make get-mixins
      - name: Login to the ghcr.io Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Publish
        run: REGISTRY=ghcr.io/vdice make publish-bundle 
