name: PR

on: [pull_request]

jobs:
  build:
    name: Build Bundles 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Bootstrap
        run: make bootstrap
      - name: Build
        run: make build-bundle
      - name: Validate
        run: make validate-bundle